
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.Components
{
	public class Gui
	{
		public static bool initialized;

		public static void Initialize (Gtk.Widget iconRenderer)
		{
			if ((initialized == false)) {
				initialized = true;
			}
		}
	}

	public class BinContainer
	{
		private Gtk.Widget child;

		private Gtk.UIManager uimanager;

		public static BinContainer Attach (Gtk.Bin bin)
		{
			// GTK2's GtkBin had no size negotiation, so Stetic forwarded size requests and
			// allocations to the child here. GTK3's GtkBin measures and allocates its child itself.
			BinContainer bc = new BinContainer ();
			bin.Added += new Gtk.AddedHandler (bc.OnAdded);
			return bc;
		}

		private void OnAdded (object sender, Gtk.AddedArgs args)
		{
			this.child = args.Widget;
		}

		public void SetUiManager (Gtk.UIManager uim)
		{
			this.uimanager = uim;
			this.child.Realized += new System.EventHandler (this.OnRealized);
		}

		private void OnRealized (object sender, System.EventArgs args)
		{
			if ((this.uimanager != null)) {
				Gtk.Widget w;
				w = this.child.Toplevel;
				if (((w != null)
							&& typeof (Gtk.Window).IsInstanceOfType (w))) {
					((Gtk.Window)(w)).AddAccelGroup (this.uimanager.AccelGroup);
					this.uimanager = null;
				}
			}
		}
	}

	public class ActionGroups
	{
		public static Gtk.ActionGroup GetActionGroup (System.Type type)
		{
			return ActionGroups.GetActionGroup (type.FullName);
		}

		public static Gtk.ActionGroup GetActionGroup (string name)
		{
			return null;
		}
	}
}
