// No using directives: every type below comes from a global using, generated by the SDK in
// obj/<configuration>/<framework>/ImplicitUsings.GlobalUsings.g.cs from the Using items.
var numbers = new List<int> (Enumerable.Range (1, 3));
int spanLength = ((ReadOnlySpan<char>)"a b".AsSpan ()).Length;
var parts = "a  b".Split (' ', StringSplitOptions.RemoveEmptyEntries);
var text = new StringBuilder ();
foreach (var n in numbers)
	text.Append (Max (n, 2));
var counts = new Counts { ["parts"] = parts.Length };
using var client = new HttpClient ();
await Task.Delay (1);
Console.WriteLine ($"{text} {spanLength} {counts["parts"]} {File.Exists ("none")} {client.Timeout}");
