#!/usr/bin/env bash
# Static migration inventory: counts the constructs that block .NET 10 / Linux / GTK3.
# Idempotent; writes docs/evidence/M0/inventory.md (or the path given as $1).
# Run inside the dev container: ./scripts/pm ./scripts/inventory.sh
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="${1:-$root/docs/evidence/M0/inventory.md}"
mkdir -p "$(dirname "$out")"
cd "$root/main"

src_dirs=(src tests)
fixtures='tests/test-projects'

# Number of .cs files (outside test fixtures) whose content matches an extended regex.
count_files() {
	grep -rlE --include='*.cs' "$1" "${src_dirs[@]}" 2>/dev/null | grep -cv "^$fixtures/" || true
}

# Number of matching lines (outside test fixtures).
# Note: grep exits 1 on "no match"; counting helpers must never abort the report.
count_lines() {
	grep -rhE --include='*.cs' "$1" "${src_dirs[@]}" 2>/dev/null | wc -l || true
}

projects() {
	find src tests msbuild -name '*.csproj' -not -path "$fixtures/*" | sort
}

{
	echo "# Migration inventory"
	echo
	echo "Generated by \`scripts/inventory.sh\` at commit \`$(git -C "$root" rev-parse --short HEAD 2>/dev/null || echo unknown)\`."
	echo "Counts exclude \`main/$fixtures\` (test data)."
	echo
	echo "## Projects"
	echo
	echo "| Metric | Value |"
	echo "|---|---|"
	echo "| csproj (src+tests+msbuild, excl. fixtures) | $(projects | wc -l) |"
	echo "| SDK-style csproj | $(projects | xargs grep -l '<Project Sdk=' | wc -l || true) |"
	echo "| csproj targeting \$(MDFrameworkVersion) / v4.x | $(projects | xargs grep -lE 'TargetFrameworkVersion>(\$\(MDFrameworkVersion\)|v4)' | wc -l || true) |"
	echo "| csproj targeting net10.0 | $(projects | xargs grep -l '<TargetFramework>net10.0' | wc -l || true) |"
	echo "| Projects in Main.sln | $(grep -c '^Project(' Main.sln) |"
	if [[ -f MonoDevelop.Linux.sln ]]; then
		echo "| Projects in MonoDevelop.Linux.sln | $(grep -c '^Project(' MonoDevelop.Linux.sln) |"
	fi
	echo "| .cs files (excl. fixtures) | $(find src tests -name '*.cs' -not -path "$fixtures/*" | wc -l) |"
	echo "| *.addin.xml manifests | $(find src tests -name '*.addin.xml' -not -path "$fixtures/*" | wc -l) |"
	echo
	echo "## Blockers (files unless noted)"
	echo
	echo "| Construct | Pattern | Count |"
	echo "|---|---|---|"
	while IFS='~' read -r name pattern mode; do
		if [[ "$mode" == lines ]]; then
			n="$(count_lines "$pattern") lines"
		else
			n="$(count_files "$pattern")"
		fi
		# shellcheck disable=SC2016 # backticks are Markdown, not command substitution
		printf '| %s | `%s` | %s |\n' "$name" "${pattern//|/\\|}" "$n"
	done <<'EOF'
GTK stack (Gtk/Gdk/Pango/Cairo/GLib/Atk)~\b(Gtk|Gdk|Pango|Cairo|GLib|Atk)\.[A-Z]~files
GTK2-only: ExposeEvent~ExposeEvent~files
GTK2-only: SizeRequested~SizeRequested~files
GTK2-only: Gdk.GC / Drawable~Gdk\.(GC|Drawable)\b~files
GTK2-only: Gtk.Rc~Gtk\.Rc\b~files
Stetic generated (gtk-gui)~Stetic\.~files
Xwt~\bXwt\.~files
Mono.Unix / Mono.Posix~Mono\.Unix~files
Mono runtime detection~Mono\.Runtime~files
Remoting: MarshalByRefObject~MarshalByRefObject~files
Remoting namespace~System\.Runtime\.Remoting~files
BinaryFormatter~BinaryFormatter~files
Delegate BeginInvoke~\.BeginInvoke *\(~files
Thread.Abort~\.Abort *\( *\)~files
Assembly.LoadFrom/LoadFile/ReflectionOnly~Assembly\.(LoadFrom|LoadFile|ReflectionOnlyLoad)~files
System.Web~System\.Web\b~files
WCF (System.ServiceModel)~System\.ServiceModel~files
System.Drawing~System\.Drawing~files
WinForms~System\.Windows\.Forms~files
Microsoft.Win32 (registry)~Microsoft\.Win32~files
CodeDom~System\.CodeDom~files
DllImport~\[DllImport~lines
Platform.IsWindows~IsWindows~files
Platform.IsMac~IsMac~files
EOF
	echo
	echo "## Native libraries imported"
	echo
	echo '| Library | DllImport lines |'
	echo '|---|---|'
	grep -rhoE --include='*.cs' 'DllImport *\( *"?[A-Za-z0-9_.@/+-]+' src tests 2>/dev/null \
		| sed -E 's/DllImport *\( *"?//' | sort | uniq -c | sort -rn | head -40 \
		| awk '{printf "| %s | %s |\n", $2, $1}' || true
	echo
	echo "## dllmap config files"
	echo
	find src -name '*.dll.config' | sort | sed 's/^/- /'
	echo
	echo "## Tests"
	echo
	echo "| Metric | Value |"
	echo "|---|---|"
	echo "| [Test] | $(count_lines '\[Test\]') |"
	echo "| [TestCase...] | $(count_lines '\[TestCase') |"
	echo "| [Ignore...] | $(count_lines '\[Ignore') |"
	echo "| Files using GuiUnit | $(count_files 'GuiUnit') |"
	echo "| TestFixtureSetUp/TearDown files | $(count_files 'TestFixture(SetUp|TearDown)') |"
	echo
	echo "### [Test]+[TestCase] per test project"
	echo
	echo '| Project dir | Tests |'
	echo '|---|---|'
	while read -r proj; do
		dir="$(dirname "$proj")"
		n="$(grep -rhE --include='*.cs' '\[(Test|TestCase)\b' "$dir" 2>/dev/null | wc -l)"
		[[ "$n" -gt 0 ]] && printf '| %s | %s |\n' "$dir" "$n"
	done < <(projects | grep -iE 'test' ) || true
	echo
	echo "## Package references (central versions from Directory.Build.props)"
	echo
	echo '```'
	grep -hoE '<NuGetVersion[A-Za-z0-9]+>[^<]+' Directory.Build.props msbuild/*.props 2>/dev/null | sed 's/<//; s/>/ = /' | sort -u || true
	echo '```'
	echo
	echo "## Submodules"
	echo
	echo '```'
	git -C "$root" submodule status 2>/dev/null || true
	echo '```'
} > "$out"

echo "inventory written to ${out#"$root"/}"
