#!/usr/bin/env bash
# Static migration inventory: counts the constructs that block .NET 10 / Linux / GTK3.
# Idempotent; writes docs/evidence/M0/inventory.md (or the path given as $1).
# Run inside the dev container: ./scripts/pm ./scripts/inventory.sh
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
linux_only=0
if [[ "${1:-}" == "--linux-sln" ]]; then
	# Count only the C# files compiled by main/MonoDevelop.Linux.sln (M5 progress metric).
	linux_only=1
	shift
fi
out="$(realpath -m "${1:-$root/docs/evidence/M0/inventory.md}")"
mkdir -p "$(dirname "$out")"
cd "$root/main"

src_dirs=(src tests)
fixtures='tests/test-projects'
test_output='tests/tmp' # git-ignored output of test runs (the only directory named tmp: grep --exclude-dir=tmp)

if [[ "$linux_only" == 1 ]]; then
	mapfile -t linux_files < <(python3 "$root/scripts/tools/linux-sln-sources.py" .)
fi

# Number of .cs files (outside test fixtures) whose content matches an extended regex.
# Note: grep exits 1 on "no match"; counting helpers must never abort the report.
count_files() {
	if [[ "$linux_only" == 1 ]]; then
		[[ ${#linux_files[@]} -gt 0 ]] || { echo 0; return; }
		grep -lE "$1" "${linux_files[@]}" 2>/dev/null | wc -l || true
	else
		grep -rlE --include='*.cs' --exclude-dir=tmp "$1" "${src_dirs[@]}" 2>/dev/null | grep -cv "^$fixtures/" || true
	fi
}

# Number of matching lines (outside test fixtures).
count_lines() {
	if [[ "$linux_only" == 1 ]]; then
		[[ ${#linux_files[@]} -gt 0 ]] || { echo 0; return; }
		cat "${linux_files[@]}" | grep -cE "$1" || true
	else
		grep -rhE --include='*.cs' --exclude-dir=tmp "$1" "${src_dirs[@]}" 2>/dev/null | wc -l || true
	fi
}

projects() {
	find src tests msbuild -name '*.csproj' -not -path "$fixtures/*" -not -path "$test_output/*" | sort
}

{
	echo "# Migration inventory"
	echo
	echo "Generated by \`scripts/inventory.sh\` at commit \`$(git -C "$root" rev-parse --short HEAD 2>/dev/null || echo unknown)\`."
	if [[ "$linux_only" == 1 ]]; then
		echo "Scope: C# files compiled by \`main/MonoDevelop.Linux.sln\` (${#linux_files[@]} files)."
	else
		echo "Counts exclude \`main/$fixtures\` (test data)."
	fi
	echo
	echo "## Projects"
	echo
	echo "| Metric | Value |"
	echo "|---|---|"
	echo "| csproj (src+tests+msbuild, excl. fixtures) | $(projects | wc -l) |"
	echo "| SDK-style csproj | $(projects | xargs -d '\n' grep -l '<Project Sdk=' | wc -l || true) |"
	echo "| csproj targeting \$(MDFrameworkVersion) / v4.x | $(projects | xargs -d '\n' grep -lE 'TargetFrameworkVersion>(\$\(MDFrameworkVersion\)|v4)' | wc -l || true) |"
	echo "| csproj targeting net10.0 | $(projects | xargs -d '\n' grep -l '<TargetFramework>net10.0' | wc -l || true) |"
	# Main.sln (218 entries in M0) was replaced by MonoDevelop.Linux.sln in M5 (ADR 0002)
	for sln in Main.sln MonoDevelop.Linux.sln; do
		if [[ -f $sln ]]; then
			echo "| Projects in $sln | $(grep -c '^Project(' "$sln") |"
		fi
	done
	echo "| .cs files (excl. fixtures) | $(find src tests -name '*.cs' -not -path "$fixtures/*" -not -path "$test_output/*" | wc -l) |"
	echo "| *.addin.xml manifests | $(find src tests -name '*.addin.xml' -not -path "$fixtures/*" -not -path "$test_output/*" | wc -l) |"
	echo
	echo "## Blockers (files unless noted)"
	echo
	echo "| Construct | Pattern | Count |"
	echo "|---|---|---|"
	while IFS='~' read -r name pattern mode; do
		if [[ "$mode" == lines ]]; then
			n="$(count_lines "$pattern") lines"
		else
			n="$(count_files "$pattern")"
		fi
		# shellcheck disable=SC2016 # backticks are Markdown, not command substitution
		printf '| %s | `%s` | %s |\n' "$name" "${pattern//|/\\|}" "$n"
	done <<'EOF'
GTK stack (Gtk/Gdk/Pango/Cairo/GLib/Atk)~\b(Gtk|Gdk|Pango|Cairo|GLib|Atk)\.[A-Z]~files
GTK2-only: ExposeEvent~\.ExposeEvent\b|\bOnExposeEvent *\(|\bExposeEventArgs\b~files
GTK2-only: SizeRequested~\.SizeRequested\b|\bOnSizeRequested *\(|\bSizeRequestedArgs\b~files
GTK2-only: Gdk.GC / Drawable~Gdk\.(GC|Drawable)\b~files
GTK2-only: Gtk.Rc~Gtk\.Rc\b~files
Stetic generated (gtk-gui)~Stetic\.~files
Xwt~\bXwt\.~files
Mono.Unix / Mono.Posix~Mono\.Unix~files
Mono runtime detection~Mono\.Runtime~files
Remoting: MarshalByRefObject~MarshalByRefObject~files
Remoting namespace (using)~using System\.Runtime\.Remoting~files
BinaryFormatter (new)~new BinaryFormatter~files
Delegate BeginInvoke~\.BeginInvoke *\(~files
Thread.Abort~\.Abort *\( *\)~files
Assembly.LoadFrom/LoadFile/ReflectionOnly~Assembly\.(LoadFrom|LoadFile|ReflectionOnlyLoad)~files
System.Web~System\.Web\b~files
WCF (System.ServiceModel)~System\.ServiceModel~files
System.Drawing~System\.Drawing~files
WinForms~System\.Windows\.Forms~files
Microsoft.Win32 (registry)~Microsoft\.Win32~files
CodeDom~System\.CodeDom~files
DllImport~\[DllImport~lines
Platform.IsWindows~IsWindows~files
Platform.IsMac~IsMac~files
EOF
	echo
	echo "## Native libraries imported"
	echo
	echo '| Library | DllImport lines |'
	echo '|---|---|'
	grep -rhoE --include='*.cs' --exclude-dir=tmp 'DllImport *\( *"?[A-Za-z0-9_.@/+-]+' src tests 2>/dev/null \
		| sed -E 's/DllImport *\( *"?//' | sort | uniq -c | sort -rn | head -40 \
		| awk '{printf "| %s | %s |\n", $2, $1}' || true
	echo
	echo "## dllmap config files"
	echo
	find src -name '*.dll.config' | sort | sed 's/^/- /'
	echo
	echo "## Tests"
	echo
	echo "| Metric | Value |"
	echo "|---|---|"
	echo "| [Test] | $(count_lines '\[Test\]') |"
	echo "| [TestCase...] | $(count_lines '\[TestCase') |"
	echo "| [Ignore...] | $(count_lines '\[Ignore') |"
	echo "| Files using GuiUnit | $(count_files 'GuiUnit') |"
	echo "| TestFixtureSetUp/TearDown files | $(count_files 'TestFixture(SetUp|TearDown)') |"
	echo
	echo "### [Test]+[TestCase] per test project"
	echo
	echo '| Project dir | Tests |'
	echo '|---|---|'
	while read -r proj; do
		dir="$(dirname "$proj")"
		n="$(grep -rhE --include='*.cs' --exclude-dir=tmp '\[(Test|TestCase)\b' "$dir" 2>/dev/null | wc -l)"
		[[ "$n" -gt 0 ]] && printf '| %s | %s |\n' "$dir" "$n"
	done < <(projects | grep -iE 'test' ) || true
	echo
	echo "## Package references (central versions from Directory.Build.props)"
	echo
	echo '```'
	grep -hoE '<NuGetVersion[A-Za-z0-9]+>[^<]+' Directory.Build.props msbuild/*.props 2>/dev/null | sed 's/<//; s/>/ = /' | sort -u || true
	echo '```'
	echo
	echo "## Submodules"
	echo
	echo '```'
	git -C "$root" submodule status 2>/dev/null || true
	echo '```'
} > "$out"

echo "inventory written to ${out#"$root"/}"
