// (Re)generates the warning baseline of one project: new warnings are errors (ADR 0018).
//
// Builds the project with warnings-as-errors disabled, collects the distinct warning IDs it produces and writes
// main/msbuild/Linux/warning-baselines/<Project>.props with <WarningsNotAsErrors> for those IDs (they stay visible as
// warnings); any other ID becomes an error. Security-relevant IDs are never baselined. Also writes the count of each ID.
// Usage: dotnet scripts/warnings-baseline.cs -- main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj

using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text.RegularExpressions;

var root = RepoRoot ();
if (args.Length != 1)
	Die ("usage: dotnet scripts/warnings-baseline.cs -- <project file (.csproj, .fsproj)>");
var project = args[0];
var name = Path.GetFileNameWithoutExtension (project);
var outDirectory = Path.Combine (root, "main", "msbuild", "Linux", "warning-baselines");
var props = Path.Combine (outDirectory, name + ".props");
var counts = Path.Combine (outDirectory, name + ".counts.txt");
Directory.CreateDirectory (outDirectory);
Directory.CreateDirectory (Path.Combine (root, "out"));

// IDs that must never be accepted as legacy noise: SYSLIB serialization, NuGet audit, analyzer load failures and all the
// security CA rules (CA2100, CA23xx, CA3xxx, CA5xxx).
var forbidden = new Regex ("^(SYSLIB0011|SYSLIB0050|SYSLIB0051|NU190[1-4]|CS8032|CS0006|CA2100|CA23[0-9][0-9]|CA3[0-9]{3}|CA5[0-9]{3})$");

var log = Path.Combine (root, "out", $"warnings-{name}.log");
Log ($"building {name} without warnings-as-errors");
// A stale baseline goes first, so that the build reflects the current code.
File.Delete (props);
if (RunToFile ("dotnet", ["build", project, "-nologo", "-clp:NoSummary", "-p:TreatWarningsAsErrors=false", "--no-incremental"], log) != 0) {
	foreach (var line in File.ReadLines (log).TakeLast (30))
		Console.Error.WriteLine (line);
	Die ("build failed; fix errors before generating a baseline");
}

// Only the warnings reported for this project: its dependencies are built too and have their own baseline.
var projectMarker = "[" + Path.GetFullPath (project);
var ids = File.ReadLines (log)
	.Where (line => line.Contains (projectMarker, StringComparison.Ordinal))
	.SelectMany (line => Regex.Matches (line, "warning ([A-Z]+[0-9]+)").Select (match => match.Groups[1].Value))
	.ToList ();
if (ids.Count == 0) {
	// No legacy warnings left: no baseline, every warning of this project is an error.
	File.Delete (counts);
	Log ($"no warnings: baseline removed for {name}");
	return 0;
}
// The layout of `sort | uniq -c | sort -rn`: most frequent first, equal counts in descending ID order.
var byId = ids.GroupBy (id => id).Select (group => (Id: group.Key, Count: group.Count ()))
	.OrderByDescending (entry => entry.Count)
	.ThenByDescending (entry => entry.Id, StringComparer.Ordinal)
	.ToList ();
var rejected = byId.Where (entry => forbidden.IsMatch (entry.Id)).ToList ();
if (rejected.Count > 0) {
	foreach (var entry in rejected)
		Console.Error.WriteLine (entry.Id);
	Die ("security-relevant warnings present; they cannot be baselined");
}

File.WriteAllLines (counts, byId.Select (entry => $"{entry.Count,7} {entry.Id}"));

var list = string.Join (';', byId.Select (entry => entry.Id).Order (StringComparer.Ordinal));
File.WriteAllText (props, $"""
	<Project>
	  <!-- Generated by scripts/warnings-baseline.cs — legacy warning IDs of {name} that stay warnings.
	       Any other warning ID is an error. Shrink this list over time. -->
	  <PropertyGroup>
	    <WarningsNotAsErrors>$(WarningsNotAsErrors);{list}</WarningsNotAsErrors>
	  </PropertyGroup>
	</Project>

	""");

Log ($"baseline: {byId.Count} IDs, {ids.Count} warnings -> {Path.GetRelativePath (root, props)}");
return 0;

static string RepoRoot ([CallerFilePath] string script = "") => Path.GetFullPath (Path.Combine (Path.GetDirectoryName (script)!, ".."));

static void Log (string message) => Console.Error.WriteLine ($"\u001b[1;34m==>\u001b[0m {message}");

[DoesNotReturn]
static void Die (string message)
{
	Console.Error.WriteLine ($"\u001b[1;31merror:\u001b[0m {message}");
	Environment.Exit (1);
}

// Standard output and error to a file, in the order they come.
static int RunToFile (string fileName, IEnumerable<string> arguments, string file)
{
	var info = new ProcessStartInfo (fileName) { UseShellExecute = false, RedirectStandardOutput = true, RedirectStandardError = true };
	foreach (var argument in arguments)
		info.ArgumentList.Add (argument);
	using var writer = new StreamWriter (file);
	using var process = new Process { StartInfo = info };
	process.OutputDataReceived += (_, e) => { if (e.Data != null) lock (writer) writer.WriteLine (e.Data); };
	process.ErrorDataReceived += (_, e) => { if (e.Data != null) lock (writer) writer.WriteLine (e.Data); };
	process.Start ();
	process.BeginOutputReadLine ();
	process.BeginErrorReadLine ();
	process.WaitForExit ();
	return process.ExitCode;
}
