#!/usr/bin/env bash
# (Re)generate the warning baseline of one project (constitution V: new warnings are errors).
#
# Builds the project with warnings-as-errors disabled, collects the distinct warning IDs it
# produces, and writes main/msbuild/Linux/warning-baselines/<Project>.props containing
# <WarningsNotAsErrors> for those IDs (they stay visible as warnings). Any other ID becomes an
# error. Security-relevant IDs are never baselined. Also writes per-ID counts for the evidence log.
#
# Usage: ./scripts/pm ./scripts/warnings-baseline.sh main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj
set -euo pipefail
# shellcheck source=scripts/lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
md_require_container "$@"

[[ $# -eq 1 ]] || md_die "usage: $0 <project.csproj>"
project="$1"
name="$(basename "$project" .csproj)"
out_dir="$MD_ROOT/main/msbuild/Linux/warning-baselines"
out="$out_dir/$name.props"
counts="$out_dir/$name.counts.txt"
mkdir -p "$out_dir" "$MD_OUT"

# IDs that must never be accepted as legacy noise.
# SYSLIB serialization, NuGet audit, analyzer load failures and all security CA rules
# (CA2100, CA23xx, CA3xxx, CA5xxx).
forbidden='^(SYSLIB0011|SYSLIB0050|SYSLIB0051|NU190[1-4]|CS8032|CS0006|CA2100|CA23[0-9][0-9]|CA3[0-9]{3}|CA5[0-9]{3})$'

log="$MD_OUT/warnings-$name.log"
md_log "building $name without warnings-as-errors"
# Remove a stale baseline first so the build reflects the current code.
rm -f "$out"
dotnet build "$project" -nologo -clp:NoSummary -p:TreatWarningsAsErrors=false --no-incremental > "$log" 2>&1 || {
	tail -30 "$log" >&2
	md_die "build failed; fix errors before generating a baseline"
}

# Only warnings reported for this project (dependencies are built too and have their own baseline).
project_abs="$(cd "$(dirname "$project")" && pwd)/$(basename "$project")"
{ grep -F "[$project_abs" "$log" || true; } | grep -oE 'warning [A-Z]+[0-9]+' | awk '{print $2}' | sort | uniq -c | sort -rn > "$counts.tmp" || true
if [[ ! -s "$counts.tmp" ]]; then
	# No legacy warnings left: no baseline, every warning of this project is an error.
	rm -f "$counts.tmp" "$counts"
	md_log "no warnings: baseline removed for $name"
	exit 0
fi
if grep -qE "$forbidden" <(awk '{print $2}' "$counts.tmp"); then
	awk '{print $2}' "$counts.tmp" | grep -E "$forbidden" >&2 || true
	rm -f "$counts.tmp"
	md_die "security-relevant warnings present; they cannot be baselined"
fi
mv "$counts.tmp" "$counts"

ids="$(awk '{print $2}' "$counts" | sort | paste -sd ';' -)"
{
	echo '<Project>'
	echo "  <!-- Generated by scripts/warnings-baseline.sh — legacy warning IDs of $name that stay warnings."
	echo '       Any other warning ID is an error (constitution V). Shrink this list over time. -->'
	echo '  <PropertyGroup>'
	echo "    <WarningsNotAsErrors>\$(WarningsNotAsErrors);$ids</WarningsNotAsErrors>"
	echo '  </PropertyGroup>'
	echo '</Project>'
} > "$out"

md_log "baseline: $(wc -l < "$counts") IDs, $(awk '{s+=$1} END {print s+0}' "$counts") warnings -> ${out#"$MD_ROOT"/}"
